---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgBbQLJ1oBX2CX5pR6OCkcncAWcBlknFt1/JkcYF/Xvbbe91G2vP4RhdO9ZXkgH53M1hbl5KanBGkpTdhmwnZ1oTohCbKdrU20V2UJUo2a7synLZAls74nJY+8SlUvKbtmC9Qg0xw17yXHwMl/ZqeipYsa/A8lRYcE0Ue9dq5tpM5FDFpAl75sWNL71oT34cQNDhumraOfBK+ME8O5A9yIvGzxe/grhDntvBUnOkTMy+yfokTwgo485Qw3tVpPgQNPVaEXMAiM2ccH+HiCpIZOaICl9jPVoG1FCJR1yltFoo5gC9+qPhF5mvFo9iQJnIo02ou3E4ZHWlbRFOA+WZW85OlZCKIKmVp7ZWTOHXWIXH52sx9OcEjLB2JAZGlCnDbq+YW4sKpW9HYEKZsjbVNQFaOwFuBBj2batxjXpQq6EpauyRCp7N50KvlAFHo5HlHNPi+q10J7WdzmLNq5ny3jWN0VucqoumbU+JtipONNFhknflpzozWO4KuJF+p5NddDue3x4VZJr9L6zN5NeiNDYkW0OAnqDAWEk/pXx3cwAR59Lb/a1ZKYVWv8q5UyYLabBH2BY0ZbyM+TlEC59fS5Q+7rledipT/WCV2xirEnYtPFO5N0kZHx6rBMGnGIeSAzk9j3MGfm7mYxTHhTyV1S0KaskSt0i7RLFZfqYMR2qmuPEWq5ycMPYp4t/jzwDXLzYX/rohdzY=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
